# Generated by Django 2.0.2 on 2018-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_items',
            options={'verbose_name_plural': 'menu_items'},
        ),
        migrations.AlterModelOptions(
            name='sub_items',
            options={'verbose_name_plural': 'sub_items'},
        ),
        migrations.AlterModelOptions(
            name='sub_of_sub_items',
            options={'verbose_name_plural': 'sub_of_sub_items'},
        ),
    ]
