# Generated by Django 2.0.2 on 2018-03-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0002_auto_20180306_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name_plural': 'research'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'slider'},
        ),
    ]
